sudo: required
services:
    - docker

before_install:
    - docker build -t omerslik/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true omerslik/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "my-slik-app"
    env: "docker"
    bucket_name: "elasticbeanstalk-us-east-1-790662091625"
    bucket_path: "my-slik-app"
    on:
        branch: master
    access_key_id: $aws_access_key
    secret_access_key: $aws_secret_key